import { Course, Question } from "./types";
export const courses:Course[]=[
{id:"ai-engineer",slug:"ai-engineer-interview",title:"AI Engineer Interview Blueprint",description:"A practical path through Python, ML systems, RAG, agents, evaluation and production questions.",role:"AI Engineer",level:"Intermediate → Advanced",duration:"8 weeks",price:1499,featured:true,cover_emoji:"◈",published:true,lessons:32},
{id:"genai",slug:"generative-ai",title:"Generative AI & RAG Mastery",description:"Embeddings, vector search, retrieval pipelines, evaluation, prompt engineering and production patterns.",role:"GenAI Engineer",level:"Intermediate",duration:"6 weeks",price:1299,featured:true,cover_emoji:"✦",published:true,lessons:27},
{id:"agentic",slug:"agentic-ai",title:"Agentic AI Engineering",description:"Build reliable tool-using agents with planning, memory, orchestration, guardrails and observability.",role:"Agentic AI",level:"Advanced",duration:"7 weeks",price:1599,featured:true,cover_emoji:"⌁",published:true,lessons:29},
{id:"data-scientist",slug:"data-scientist",title:"Data Scientist Interview Lab",description:"Statistics, ML, SQL, experimentation, case studies and Python interview drills.",role:"Data Scientist",level:"Intermediate",duration:"7 weeks",price:1399,featured:false,cover_emoji:"▦",published:true,lessons:31},
{id:"python",slug:"python-coding",title:"Python Coding for AI Interviews",description:"From fundamentals to data structures, algorithms and ML-flavoured coding questions.",role:"All AI Roles",level:"Beginner → Advanced",duration:"5 weeks",price:999,featured:false,cover_emoji:"⌘",published:true,lessons:40},
{id:"ml",slug:"machine-learning",title:"Machine Learning Interview System",description:"Model selection, feature engineering, metrics, debugging, system design and ML case interviews.",role:"ML Engineer",level:"Intermediate",duration:"6 weeks",price:1199,featured:false,cover_emoji:"△",published:true,lessons:25},
{id:"genai-bank",slug:"genai-engineer-interview-bank-india",title:"GenAI Engineer Interview Question Bank — India",description:"A focused, practical interview bank for GenAI Engineer roles across Indian product and IT companies. RAG, LLMs, agents, evaluation, Python and system design.",role:"GenAI Engineer",level:"Intermediate → Advanced",duration:"Self paced",price:199,featured:true,cover_emoji:"₹",published:true,lessons:0}
];
export const questions:Question[]=[
{id:"q1",category:"RAG",role:"AI Engineer",difficulty:"Hard",question:"Why can a high-recall retriever still produce a poor RAG answer?",answer:"Retrieval recall only measures whether relevant evidence was retrieved. Ranking quality, context packing, chunk boundaries, prompt grounding and generation can still cause the model to miss or distort the useful evidence.",tags:["retrieval","evaluation"]},
{id:"q2",category:"Python",role:"AI Engineer",difficulty:"Medium",question:"Implement a function that returns the first non-repeating character in a string in O(n).",answer:"Use a frequency dictionary in one pass, then scan the string again. This is O(n) time and O(k) space.",tags:["python","hashmap"]},
{id:"q3",category:"Agents",role:"Agentic AI",difficulty:"Hard",question:"When should an agent use a deterministic workflow instead of autonomous planning?",answer:"Use deterministic orchestration when the task has stable steps, strict compliance requirements, predictable failure modes or high cost of wrong tool calls. Agents are most useful where decisions genuinely require adaptive planning.",tags:["agents","architecture"]},
{id:"q4",category:"Statistics",role:"Data Scientist",difficulty:"Medium",question:"What is the difference between precision and recall, and when would you prioritize each?",answer:"Precision measures the fraction of predicted positives that are correct; recall measures the fraction of actual positives found. Prioritize precision when false positives are costly and recall when false negatives are costly.",tags:["statistics","metrics"]}
];
