import { Question } from "./types";

export const genaiBankQuestions: Question[] = [
  { id:"genai-1", category:"RAG", role:"GenAI Engineer", difficulty:"Hard", question:"Design a production RAG system for a large Indian enterprise. How would you control hallucinations, retrieval quality and sensitive data?", answer:"Cover hybrid retrieval, chunking, metadata filters, reranking, access-aware retrieval, grounded generation, citations, PII controls, evaluation datasets, observability and safe fallbacks.", tags:["rag","security","system-design"] },
  { id:"genai-2", category:"LLM", role:"GenAI Engineer", difficulty:"Hard", question:"An LLM application is accurate in offline testing but fails after deployment. How would you diagnose the issue?", answer:"Separate retrieval, prompt, model, tool and data-drift failures. Trace production requests, inspect retrieved context, compare online/offline distributions, slice failures and add regression tests.", tags:["llm","debugging","observability"] },
  { id:"genai-3", category:"RAG", role:"GenAI Engineer", difficulty:"Hard", question:"Your RAG retriever finds the correct document but the model still gives the wrong answer. What would you investigate?", answer:"Check chunk boundaries, ranking position, context ordering, context-window pressure, prompt grounding instructions, conflicting passages and whether the generator is actually using retrieved evidence.", tags:["rag","retrieval","prompting"] },
  { id:"genai-4", category:"Embeddings", role:"GenAI Engineer", difficulty:"Medium", question:"How would you choose an embedding model for an enterprise GenAI application used across English and Indian-language content?", answer:"Evaluate language coverage, domain similarity, retrieval quality, latency, dimensionality and licensing. Benchmark on a representative multilingual query-document dataset rather than choosing from leaderboard scores alone.", tags:["embeddings","multilingual","evaluation"] },
  { id:"genai-5", category:"Vector DB", role:"GenAI Engineer", difficulty:"Hard", question:"When would you use hybrid search instead of pure vector search in a production RAG application?", answer:"Use hybrid search when exact terms, IDs, product names, error codes or domain vocabulary matter alongside semantic similarity. Combine lexical and dense retrieval and evaluate recall and ranking together.", tags:["vector-db","hybrid-search","retrieval"] },
  { id:"genai-6", category:"Agents", role:"GenAI Engineer", difficulty:"Hard", question:"How would you prevent an agent from making an unsafe tool call in production?", answer:"Use allowlisted tools, strict schemas, authorization checks, argument validation, policy/guardrail layers, human approval for high-impact actions, timeouts, audit logs and least-privilege credentials.", tags:["agents","security","guardrails"] },
  { id:"genai-7", category:"Evaluation", role:"GenAI Engineer", difficulty:"Hard", question:"How would you evaluate a RAG system before deploying it to a large enterprise?", answer:"Build a versioned evaluation set and measure retrieval recall/precision, answer correctness, groundedness, citation quality, refusal behavior, latency, cost and failure rates across important user segments.", tags:["evaluation","rag","metrics"] },
  { id:"genai-8", category:"Python", role:"GenAI Engineer", difficulty:"Medium", question:"A Python service calling an LLM becomes slow when traffic increases. What changes would you consider first?", answer:"Profile the request path, reuse HTTP clients, add async/concurrency where appropriate, batch compatible work, stream responses, cache deterministic results, control retries and monitor provider latency and rate limits.", tags:["python","performance","llm"] },
  { id:"genai-9", category:"System Design", role:"GenAI Engineer", difficulty:"Hard", question:"Design a multi-tenant GenAI platform where each customer must only retrieve its own documents.", answer:"Enforce tenant identity at authentication and authorization boundaries, store tenant metadata with documents, apply server-side retrieval filters, isolate indexes where required, prevent client-controlled tenant IDs and test cross-tenant leakage explicitly.", tags:["system-design","multi-tenant","security"] },
  { id:"genai-10", category:"Indian Interviews", role:"GenAI Engineer", difficulty:"Hard", question:"An interviewer asks: 'Why should we hire you as a GenAI Engineer instead of a prompt engineer?' How would you answer?", answer:"Differentiate by showing end-to-end engineering: data and retrieval pipelines, model selection, evaluation, backend APIs, security, observability, deployment, cost/latency trade-offs and production reliability—not just prompt writing.", tags:["interview","career","system-design"] },
];
