"use client";
import { useEffect, useState } from "react";
import { Bot, DollarSign, FilePlus2, LibraryBig, Plus, Save, Sparkles, Trash2 } from "lucide-react";

type Course={id:string;slug:string;title:string;description:string;role:string;level:string;duration:string;price:number;published:boolean;featured:boolean;cover_emoji:string};
type Material={id:string;title:string;content_type:string;difficulty:string;status:string;created_at:string};
const empty={title:"",slug:"",description:"",role:"GenAI Engineer",level:"Intermediate",duration:"Self paced",price:199,published:true,featured:false,cover_emoji:"✦"};

export default function AdminStudio(){
 const [tab,setTab]=useState("products"); const [courses,setCourses]=useState<Course[]>([]); const [materials,setMaterials]=useState<Material[]>([]); const [form,setForm]=useState(empty); const [materialTitle,setMaterialTitle]=useState(""); const [materialText,setMaterialText]=useState(""); const [question,setQuestion]=useState(""); const [answer,setAnswer]=useState(""); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState(""); const [topic,setTopic]=useState("GenAI Engineer interview questions for Indian product and IT companies: Python, LLMs, RAG, agents, evaluation and system design"); const [type,setType]=useState("question_set"); const [level,setLevel]=useState("Hard"); const [result,setResult]=useState("");
 const load=async()=>{const [c,m]=await Promise.all([fetch("/api/admin/courses"),fetch("/api/admin/materials")]); if(c.ok)setCourses((await c.json()).courses||[]); if(m.ok)setMaterials((await m.json()).materials||[])};
 useEffect(()=>{load()},[]);
 const update=(k:string,v:unknown)=>setForm(f=>({...f,[k]:v}));
 const saveCourse=async()=>{setBusy(true);setMsg("");try{const r=await fetch("/api/admin/courses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)throw Error(j.error);setMsg("Product created.");setForm(empty);await load()}catch(e){setMsg(e instanceof Error?e.message:"Save failed")}finally{setBusy(false)}};
 const savePrice=async(c:Course)=>{const next=window.prompt(`Price for ${c.title} (₹)`,String(c.price));if(next===null)return;const price=Number(next);if(!Number.isFinite(price)||price<0)return setMsg("Enter a valid price.");const r=await fetch("/api/admin/courses",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:c.id,price})});const j=await r.json();if(!r.ok)setMsg(j.error||"Price update failed");else{setMsg(`Price updated to ₹${price}.`);await load()}};
 const togglePublish=async(c:Course)=>{await fetch("/api/admin/courses",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:c.id,published:!c.published})});await load()};
 const deleteCourse=async(c:Course)=>{if(!window.confirm(`Delete ${c.title}?`))return;await fetch("/api/admin/courses",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:c.id})});await load()};
 const saveMaterial=async()=>{setBusy(true);try{const r=await fetch("/api/admin/materials",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:materialTitle,source_brief:materialText,content_type:"manual_material",difficulty:"Hard",content:{body:materialText},status:"draft"})});const j=await r.json();if(!r.ok)throw Error(j.error);setMsg("Material saved as draft.");setMaterialTitle("");setMaterialText("");await load()}catch(e){setMsg(e instanceof Error?e.message:"Save failed")}finally{setBusy(false)}};
 const saveQuestion=async()=>{setBusy(true);try{const r=await fetch("/api/admin/questions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({category:"GenAI",role:"GenAI Engineer",difficulty:"Hard",question,answer,tags:["genai","rag","indian-interviews"]})});const j=await r.json();if(!r.ok)throw Error(j.error);setMsg("Interview question added.");setQuestion("");setAnswer("")}catch(e){setMsg(e instanceof Error?e.message:"Save failed")}finally{setBusy(false)}};
 const generate=async()=>{setBusy(true);setResult("");try{const r=await fetch("/api/admin/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic,type,level})});const j=await r.json();if(!r.ok)throw Error(j.error);setResult(JSON.stringify(j.content,null,2))}catch(e){setResult(JSON.stringify({error:e instanceof Error?e.message:"Generation failed"},null,2))}finally{setBusy(false)}};
 return <main className="page"><div className="container"><span className="eyebrow"><Sparkles size={13}/> Veyrin Control Center</span><h1 className="page-title">Manage the learning business.</h1><p className="sub">Create products, change prices, publish interview material and use AI to accelerate content production.</p>
 <div className="admin-layout" style={{marginTop:28}}><aside className="admin-nav"><button className={`side-link ${tab==="products"?"active":""}`} onClick={()=>setTab("products")}><DollarSign size={16}/> Products & prices</button><button className={`side-link ${tab==="material"?"active":""}`} onClick={()=>setTab("material")}><FilePlus2 size={16}/> Add material</button><button className={`side-link ${tab==="questions"?"active":""}`} onClick={()=>setTab("questions")}><LibraryBig size={16}/> Interview bank</button><button className={`side-link ${tab==="ai"?"active":""}`} onClick={()=>setTab("ai")}><Bot size={16}/> AI Studio</button></aside>
 <section className="admin-main">{msg&&<div className="success" style={{marginBottom:14}}>{msg}</div>}
 {tab==="products"&&<><div className="card"><h2>Products & pricing</h2><p className="sub">The featured launch product is the GenAI Engineer Interview Question Bank at ₹199.</p><div className="table-wrap"><table className="table"><thead><tr><th>Product</th><th>Role</th><th>Price</th><th>Status</th><th>Actions</th></tr></thead><tbody>{courses.map(c=><tr key={c.id}><td><strong>{c.cover_emoji} {c.title}</strong><div className="muted-cell">/{c.slug}</div></td><td>{c.role}</td><td><strong>₹{c.price}</strong></td><td><span className="pill">{c.published?"Published":"Draft"}</span></td><td><div className="action-row"><button className="btn" onClick={()=>savePrice(c)}>Change price</button><button className="btn" onClick={()=>togglePublish(c)}>{c.published?"Unpublish":"Publish"}</button><button className="btn danger-btn" onClick={()=>deleteCourse(c)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div></div><div className="card" style={{marginTop:18}}><h3><Plus size={17}/> Add a product</h3><div className="form-grid">{[["title","Product title"],["slug","Slug"],["role","Role"],["level","Level"],["duration","Duration"],["price","Price (₹)"],["cover_emoji","Icon"]].map(([k,l])=><div className="field" key={k}><label>{l}</label><input className="input" value={String((form as any)[k])} onChange={e=>update(k,k==="price"?Number(e.target.value):e.target.value)}/></div>)}<div className="field full"><label>Description</label><textarea className="input textarea" value={form.description} onChange={e=>update("description",e.target.value)}/></div></div><button className="btn primary" style={{marginTop:14}} disabled={busy} onClick={saveCourse}><Save size={15}/> Create product</button></div></>}
 {tab==="material"&&<div className="card"><h2>Add learning material</h2><p className="sub">Paste notes, interview explanations, study material or a source brief. It is stored as a reviewable draft.</p><div className="field"><label>Title</label><input className="input" value={materialTitle} onChange={e=>setMaterialTitle(e.target.value)} placeholder="RAG Interview Notes — Retrieval & Evaluation"/></div><div className="field" style={{marginTop:14}}><label>Material</label><textarea className="input textarea" style={{minHeight:280}} value={materialText} onChange={e=>setMaterialText(e.target.value)} placeholder="Paste your material here..."/></div><button className="btn primary" style={{marginTop:14}} disabled={busy||!materialTitle||!materialText} onClick={saveMaterial}><Save size={15}/> Save material</button><h3 style={{marginTop:30}}>Recent drafts</h3>{materials.map(m=><div className="draft-row" key={m.id}><div><strong>{m.title}</strong><div className="muted-cell">{m.content_type} · {m.difficulty}</div></div><span className="pill">{m.status}</span></div>)}</div>}
 {tab==="questions"&&<div className="card"><h2>GenAI Engineer interview bank</h2><p className="sub">Add India-focused questions. The launch product can be sold for ₹199 through Razorpay when payments are connected.</p><div className="field"><label>Question</label><textarea className="input textarea" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Design a production RAG system for a large Indian enterprise. How would you handle retrieval quality, PII and hallucination control?"/></div><div className="field" style={{marginTop:14}}><label>Ideal answer / evaluation points</label><textarea className="input textarea" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Key points expected from a strong candidate..."/></div><button className="btn primary" style={{marginTop:14}} disabled={busy||!question||!answer} onClick={saveQuestion}><Plus size={15}/> Add question</button></div>}
 {tab==="ai"&&<><div className="ai-box"><h3><Bot size={18}/> AI material generator</h3><div className="field"><label>Topic / source brief</label><textarea className="input textarea" value={topic} onChange={e=>setTopic(e.target.value)}/></div><div className="form-grid" style={{marginTop:14}}><div className="field"><label>Content type</label><select className="input" value={type} onChange={e=>setType(e.target.value)}><option value="question_set">Interview question set</option><option value="lesson">Course lesson</option><option value="coding_set">Python coding set</option><option value="revision_notes">Revision notes</option><option value="mock_interview">Mock interview</option></select></div><div className="field"><label>Difficulty</label><select className="input" value={level} onChange={e=>setLevel(e.target.value)}><option>Beginner</option><option>Medium</option><option>Hard</option><option>Expert</option></select></div></div><button className="btn primary" style={{marginTop:14}} disabled={busy} onClick={generate}><Sparkles size={15}/>{busy?"Generating...":"Generate with AI"}</button></div>{result&&<div className="card"><h3>Generated draft</h3><pre className="jsonbox">{result}</pre></div>}</>}
 </section></div></div></main>
}
