"use client";
import { useMemo, useState } from "react";
import { Check, ChevronRight, Code2, Lightbulb, Loader2, RotateCcw } from "lucide-react";

type P={id:string;title:string;category:string;difficulty:string;prompt:string;starter_code:string;course_id?:string|null};
export default function PythonPractice({questions}:{questions:P[]}){
 const categories=useMemo(()=>["All",...Array.from(new Set(questions.map(q=>q.category).filter(Boolean)))],[questions]);
 const[category,setCategory]=useState("All");const[index,setIndex]=useState(0);const[code,setCode]=useState("");const[solution,setSolution]=useState<any>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 const filtered=useMemo(()=>category==="All"?questions:questions.filter(q=>q.category===category),[questions,category]);const q=filtered[index];
 if(!q)return <main className="page"><div className="container"><div className="empty">No Python practice questions are available yet. Admin can add them category-wise.</div></div></main>;
 const reset=()=>{setCode(q.starter_code||"");setSolution(null);setError("")};
 const submit=async()=>{if(!code.trim())return setError("Write your code before submitting.");setBusy(true);setError("");try{const r=await fetch(`/api/coding/questions/${q.id}/solution`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code})});const j=await r.json();if(!r.ok)throw Error(j.error||"Could not reveal the solution");setSolution(j)}catch(e){setError(e instanceof Error?e.message:"Could not reveal the solution")}finally{setBusy(false)}};
 const next=()=>{const ni=index>=filtered.length-1?0:index+1;setIndex(ni);setSolution(null);setError("");setCode(filtered[ni]?.starter_code||"")};
 const changeCategory=(c:string)=>{setCategory(c);setIndex(0);setSolution(null);setError("");setCode((c==="All"?questions[0]:questions.find(x=>x.category===c))?.starter_code||"")};
 return <main className="page"><div className="container"><span className="eyebrow"><Code2 size={13}/> Python Coding Lab</span><h1 className="page-title">Code like the interview is real.</h1><p className="sub">Choose a category, solve the problem, submit your code, then compare it with the expected solution. No score is recorded.</p><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:22}}>{categories.map(c=><button key={c} className={`btn ${category===c?"primary":""}`} onClick={()=>changeCategory(c)}>{c}</button>)}</div><div style={{display:"grid",gridTemplateColumns:".85fr 1.15fr",gap:18,marginTop:24}}><section className="card"><div style={{display:"flex",justifyContent:"space-between",gap:10}}><span className="pill">{q.category}</span><span style={{color:"var(--muted)",fontSize:13}}>{index+1}/{filtered.length}</span></div><h2 style={{marginTop:18}}>{q.title}</h2><p style={{lineHeight:1.8,color:"var(--muted)",whiteSpace:"pre-wrap"}}>{q.prompt}</p><div className="notice" style={{marginTop:18}}><Lightbulb size={16}/> Submit your code first. The correct code is revealed only after submission.</div>{error&&<div className="error" style={{marginTop:12}}>{error}</div>}</section><section className="card"><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><strong>Python editor</strong><span className="pill">{q.difficulty}</span></div><textarea className="input textarea" value={code} onChange={e=>setCode(e.target.value)} spellCheck={false} style={{fontFamily:"ui-monospace,SFMono-Regular,Menlo,monospace",minHeight:330}} disabled={Boolean(solution)}/><div style={{display:"flex",gap:10,marginTop:14,flexWrap:"wrap"}}>{!solution?<button className="btn primary" onClick={submit} disabled={busy}>{busy?<Loader2 size={16} className="spin"/>:<Check size={16}/>} {busy?"Checking…":"Submit code"}</button>:<button className="btn primary" onClick={next}><ChevronRight size={16}/> Next problem</button>}<button className="btn" onClick={reset}><RotateCcw size={16}/> Reset</button></div>{solution&&<div className="success" style={{marginTop:18}}><strong>Expected solution</strong><pre style={{whiteSpace:"pre-wrap",overflowX:"auto",marginTop:10,fontFamily:"ui-monospace,monospace"}}>{solution.expected_code}</pre>{solution.explanation&&<p style={{whiteSpace:"pre-wrap",lineHeight:1.7}}>{solution.explanation}</p>}{solution.complexity&&<strong>Complexity: {solution.complexity}</strong>}</div>}</section></div></div></main>
}
