import Link from "next/link";import {ArrowRight,BrainCircuit,Code2,Layers3,MessageSquareText,PlayCircle,Sparkles,Target,Timer,Workflow} from "lucide-react";import {courses} from "@/lib/demo-data";
import {createAdminClient} from "@/lib/supabase/admin";
import {FileText,LockKeyhole} from "lucide-react";
export default async function Home(){let materials:any[]=[];try{const {data}=await createAdminClient().from("materials").select("id,title,slug,description,access_type,content_type").eq("published",true).eq("featured",true).order("created_at",{ascending:false}).limit(3);materials=data||[]}catch{}return <main><section className="hero"><div className="container"><span className="eyebrow"><Sparkles size={13}/> Built for the modern AI job market</span><h1>Prepare for the role.<br/><span className="gradient">Not just the interview.</span></h1><p>Veyrin combines role-specific interview preparation, Python coding drills, practical AI/ML courses and future-ready learning paths for ambitious technology professionals.</p><div className="hero-actions"><Link className="btn primary" href="/courses">Explore the learning paths <ArrowRight size={17}/></Link><Link className="btn" href="/interview">Try Interview Lab</Link></div><div className="proof"><div><strong>6</strong>career tracks</div><div><strong>100+</strong>question-ready architecture</div><div><strong>Python</strong>coding practice</div><div><strong>AI-first</strong>content studio</div></div></div></section>
<section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">What you get</span><h2>Everything around the interview.</h2></div><p>Most learning platforms stop at courses. Veyrin is designed around the full journey: learn → practise → explain → interview → improve.</p></div><div className="grid"><Feature icon={<Target/>} title="Role-specific preparation" text="Separate learning paths for AI Engineer, GenAI, Agentic AI, ML Engineer and Data Scientist roles."/><Feature icon={<MessageSquareText/>} title="Interview question bank" text="Technical, scenario, system-design and behavioural questions with answer frameworks."/><Feature icon={<Code2/>} title="Python coding lab" text="Progressive coding questions, patterns, hints and interview-style constraints."/><Feature icon={<BrainCircuit/>} title="AI-assisted learning" text="Turn a topic, JD or rough notes into structured questions, lessons and revision material."/><Feature icon={<PlayCircle/>} title="Courses + video" text="Native course lessons today, YouTube embeds now, and premium video courses later."/><Feature icon={<Workflow/>} title="Practical projects" text="Move from theory to portfolio-ready projects that mirror real corporate AI work."/></div></div></section>
<section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">Featured paths</span><h2>Choose your target role.</h2></div><Link href="/courses" className="btn">View all courses</Link></div><div className="course-grid">{courses.slice(0,3).map(c=><CourseCard key={c.id} c={c}/>)}</div></div></section>
<section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow"><FileText size={13}/> Interview material</span><h2>Study material for the interview.</h2></div><Link href="/materials" className="btn">View all material</Link></div><div className="course-grid">{(materials||[]).map((m:any)=><Link key={m.id} href={`/materials/${m.slug}`} className="card course"><div className="course-top"><span style={{fontSize:40}}>{m.access_type==="paid"?<LockKeyhole/>:<FileText/>}</span><span className="pill">{m.access_type==="paid"?"Premium":"Free"}</span></div><div className="course-body"><h3>{m.title}</h3><p>{m.description||"Interview-focused study material from Veyrin."}</p><div className="meta"><span>{m.content_type.toUpperCase()}</span></div><span className="btn primary" style={{display:"inline-flex",marginTop:15}}>Open material <ArrowRight size={15}/></span></div></Link>)}{!(materials||[]).length&&<div className="empty" style={{gridColumn:"1/-1"}}>Interview material will appear here as soon as you publish it from Admin → Add material.</div>}</div></div></section>
<section className="section"><div className="container"><div className="band"><div><span className="eyebrow">Coming next</span><h2 style={{margin:"10px 0 5px",fontSize:28}}>Your AI interview coach.</h2><p style={{margin:0,color:"var(--muted)"}}>Practice role-specific questions, get structured feedback and track weak areas.</p></div><Link href="/interview" className="btn primary">Open Interview Lab</Link></div></div></section>
<section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">How Veyrin works</span><h2>A system, not a content dump.</h2></div></div><div className="grid"><Step n="01" icon={<Layers3/>} title="Build foundations" text="Learn the core concepts through focused modules and practical examples."/><Step n="02" icon={<Timer/>} title="Train under pressure" text="Use interview questions and coding drills that force concise, structured thinking."/><Step n="03" icon={<Sparkles/>} title="Turn gaps into progress" text="Use AI-assisted revision and track the topics that need more work."/></div></div></section></main>}
function Feature({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <article className="card"><div className="iconbox">{icon}</div><h3>{title}</h3><p>{text}</p></article>}
function Step({n,icon,title,text}:{n:string,icon:React.ReactNode,title:string,text:string}){return <article className="card"><div style={{display:"flex",justifyContent:"space-between"}}><div className="iconbox">{icon}</div><span style={{color:"var(--muted)",fontWeight:900}}>{n}</span></div><h3>{title}</h3><p>{text}</p></article>}
function CourseCard({c}:{c:(typeof courses)[number]}){return <Link href={`/courses/${c.slug}`} className="card course"><div className="course-top"><span style={{fontSize:44}}>{c.cover_emoji}</span><span className="pill">{c.role}</span></div><div className="course-body"><h3>{c.title}</h3><p>{c.description}</p><div className="meta"><span>{c.level}</span><span>{c.duration}</span><span>{c.lessons} lessons</span></div><div className="price">₹{c.price.toLocaleString("en-IN")}</div><span className="btn primary" style={{display:"inline-flex"}}>View path <ArrowRight size={15}/></span></div></Link>}
