"use client";
import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import Link from "next/link";
import { ArrowRight, KeyRound, LogIn, UserPlus } from "lucide-react";
import { VeyrinBrand } from "@/components/brand";

function safeNext(value:string|null){if(!value||!value.startsWith("/")||value.startsWith("//"))return null;return value}

export default function Login(){
 const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[mode,setMode]=useState<"login"|"signup">("login");const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);const[resetMode,setResetMode]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();setMsg("");setBusy(true);try{const sb=createClient();if(resetMode){const next=safeNext(new URLSearchParams(window.location.search).get("next"))||"/dashboard";const{error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/auth/callback?next=${encodeURIComponent(`/reset-password?next=${encodeURIComponent(next)}`)}`});if(error)throw error;setMsg("If an account exists for this email, Supabase has sent a password reset link. Check your inbox.");return}const result=mode==="login"?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password});if(result.error)throw result.error;if(mode==="signup"){setMsg("Account created. Check your email if confirmation is enabled, then sign in.");setMode("login");return}const check=await fetch("/api/auth",{cache:"no-store"});const data=await check.json();const next=safeNext(new URLSearchParams(window.location.search).get("next"));window.location.href=data.isAdmin?"/admin":(next||"/dashboard")}catch(err){setMsg(err instanceof Error?err.message:"Unable to complete authentication.")}finally{setBusy(false)}};
 return <main className="page auth-page"><div className="container auth-shell"><div className="auth-card card"><div className="auth-brand"><VeyrinBrand link={false}/></div><span className="eyebrow">{resetMode?"Reset your password":mode==="login"?"Welcome back":"Create your account"}</span><h1 className="page-title auth-title">{resetMode?"Get back into Veyrin.":mode==="login"?"Sign in to Veyrin.":"Join Veyrin."}</h1><p className="sub">{resetMode?"Enter your email and Supabase will send a secure reset link.":mode==="login"?"Access your learning, interview practice and purchased content.":"One account for learning, interview practice and your dashboard."}</p><form onSubmit={submit} className="auth-form"><div className="field"><label>Email address</label><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email" required/></div>{!resetMode&&<div className="field"><label>Password</label><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 6 characters" autoComplete={mode==="login"?"current-password":"new-password"} required minLength={6}/><div className="muted-cell">Password is case-sensitive.</div></div>}<button className="btn primary auth-submit" type="submit" disabled={busy}>{resetMode?<KeyRound size={17}/>:mode==="login"?<LogIn size={17}/>:<UserPlus size={17}/>} {busy?"Please wait...":resetMode?"Send reset link":mode==="login"?"Sign in":"Create account"} {!busy&&<ArrowRight size={16}/>}</button></form>{msg&&<div className={msg.startsWith("If an account")||msg.startsWith("Account")?"success":"error"} style={{marginTop:15}}>{msg}</div>}{!resetMode&&mode==="login"&&<button className="auth-switch" onClick={()=>{setResetMode(true);setMsg("")}}>Forgot password?</button>}{resetMode&&<button className="auth-switch" onClick={()=>{setResetMode(false);setMsg("")}}>← Back to sign in</button>}{!resetMode&&<button className="auth-switch" onClick={()=>{setMode(mode==="login"?"signup":"login");setMsg("")}}>{mode==="login"?"New to Veyrin? Create an account":"Already have an account? Sign in"}</button>}<p className="auth-note">Passwords are case-sensitive. Supabase handles authentication and password reset securely. Eligible admin accounts are sent to the Admin dashboard.</p></div><Link href="/" className="back-link">← Back to Veyrin</Link></div></main>
}
